"""add description to accounts

Revision ID: 398f3fd4e216
Revises: 49f356c914f2
Create Date: 2026-05-02 15:47:14.559411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "398f3fd4e216"
down_revision: Union[str, None] = "49f356c914f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts", sa.Column("description", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "description")
    # ### end Alembic commands ###
